backend:
  name: github
  repo: melhotiby/test-react # Path to your GitHub repository
media_folder: '/assets'
collections:
  - name: "locale" # Used in routes, e.g., /admin/collections/blog
    label: "locale" # Used in the UI
    folder: "src/locales" # The path to the folder where the documents are stored
    format: 'json'
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
